"""Magnet Cylinder class code"""

import numpy as np
from magpylib._lib.obj_classes.class_BaseGeo import BaseGeo
from magpylib._lib.obj_classes.class_BaseDisplayRepr import BaseDisplayRepr
from magpylib._lib.obj_classes.class_BaseGetBH import BaseGetBH
from magpylib._lib.obj_classes.class_BaseExcitations import BaseHomMag
from magpylib._lib.config import Config
from magpylib._lib.input_checks import check_vector_format_dim_cyl, check_vector_type

# init for tool tips
d=h=di=phi1=phi2=None
mx=my=mz=None

# ON INTERFACE
class Cylinder(BaseGeo, BaseDisplayRepr, BaseGetBH, BaseHomMag):
    """
    Cylinder or Cylinder-Tile magnet with homogeneous magnetization.

    Local object coordinates: The geometric center of the full Cylinder is located
    in the origin of the local object coordinate system. The Cylinder axis conincides
    with the local CS z-axis. Local (Cylinder) and global CS coincide when
    position=(0,0,0) and orientation=unit_rotation.

    Parameters
    ----------
    magnetization: array_like, shape (3,)
        Magnetization vector (mu0*M, remanence field) in units of [mT] given in
        the local CS of the Cylinder object.

    dimension: array_like, shape (2,) or (5,)
        Dimension/Size of the solid Cylinder with diameter/height (d,h) in units of [mm]
        or of a Cylinder-Tile (r1,r2,phi1,phi2,h) where r1 < r2 denote inner and outer
        radius in units of [mm], phi1 < phi2 denote the Cylinder section angles in units
        of [deg] and h the Cylinder height in units of [mm].

    position: array_like, shape (3,) or (M,3), default=(0,0,0)
        Object position (local CS origin) in the global CS in units of [mm].
        For M>1, the position represents a path. The position and orientation
        parameters must always be of the same length.

    orientation: scipy Rotation object with length 1 or M, default=unit rotation
        Object orientation (local CS orientation) in the global CS. For M>1
        orientation represents different values along a path. The position and
        orientation parameters must always be of the same length.

    Returns
    -------
    Cylinder object: Cylinder

    Examples
    --------
    By default a Cylinder is initialized at position (0,0,0), with unit rotation:

    >>> import magpylib as mag3
    >>> magnet = mag3.magnet.Cylinder(magnetization=(100,100,100), dimension=(1,1))
    >>> print(magnet.position)
    [0. 0. 0.]
    >>> print(magnet.orientation.as_quat())
    [0. 0. 0. 1.]

    Cylinders are magnetic field sources. Below we compute the H-field [kA/m] of the
    above Cylinder at the observer position (1,1,1),

    >>> H = magnet.getH((1,1,1))
    >>> print(H)
    [1.95851744 1.95851744 1.8657571 ]

    or at a set of observer positions:

    >>> H = magnet.getH([(1,1,1), (2,2,2), (3,3,3)])
    >>> print(H)
    [[1.95851744 1.95851744 1.8657571 ]
     [0.24025917 0.24025917 0.23767364]
     [0.07101874 0.07101874 0.07068512]]

    The same result is obtained when the Cylinder moves along a path,
    away from the observer:

    >>> magnet.move([(-1,-1,-1), (-2,-2,-2)], start=1)
    >>> H = magnet.getH((1,1,1))
    >>> print(H)
    [[1.95851744 1.95851744 1.8657571 ]
     [0.24025917 0.24025917 0.23767364]
     [0.07101874 0.07101874 0.07068512]]

    A Cylinder-Tile with inner radius r1=1, outer radius r2=2, spanning over 90 deg in the
    positive quadrant of the local CS and height h=5 can be generated by setting the
    dimension=(r1,r2,phi1,phi2,h)

    >>> import magpylib as mag3
    >>> magnet = mag3.magnet.Cylinder(magnetization=(100,100,100), dimension=(1,2,0,90,5))
    >>> B = magnet.getB((1,2,3))
    >>> print(B)
    [-2.74825633  9.77282601 21.43280135]
    """

    def __init__(
            self,
            magnetization = (mx,my,mz),
            dimension = (d,h,di,phi1,phi2),
            position = (0,0,0),
            orientation = None):

        # inherit base_geo class
        BaseGeo.__init__(self, position, orientation)
        BaseDisplayRepr.__init__(self)
        BaseHomMag.__init__(self, magnetization)

        # set attributes
        self.dimension = dimension
        self.object_type = 'Cylinder'

    @property
    def dimension(self):
        """ Object dimension attribute getter and setter.
        """
        return self._dimension

    @dimension.setter
    def dimension(self, dim):
        """ Set Cylinder dimension (d,h) or (d,h,di) or (d,h,di,phi1,phi2)
            shape (2,) or (3,) or (5,), [mm, deg].
        """
        # input type and init check
        if Config.CHECK_INPUTS:
            check_vector_type(dim, 'dimension')
            #check_vector_init(dim, 'dimension')

        # input type -> ndarray
        dim = np.array(dim,dtype=float)

        # input format check
        if Config.CHECK_INPUTS:
            check_vector_format_dim_cyl(dim)

        self._dimension = dim
