# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2026.04.04
_src_path: gh:scientific-python/cookie
backend: hatch
docs: sphinx
email: magpylib@gmail.com
full_name: Michael Ortner
license: BSD
org: magpylib
project_name: magpylib
project_short_description: Python package for computation of magnetic fields of magnets,
    currents and moments.
url: https://github.com/magpylib/magpylib
vcs: true
