# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    # for pyvista
    - libgl1-mesa-dev
  commands:
    - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | gpg
      --dearmor > /usr/share/keyrings/google-linux-signing-keyring.gpg
    - echo "deb [arch=amd64
      signed-by=/usr/share/keyrings/google-linux-signing-keyring.gpg]
      http://dl.google.com/linux/chrome/deb/ stable main" >
      /etc/apt/sources.list.d/google-chrome.list
    - apt-get update
    - apt-get install -y google-chrome-stable
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv venv
    - uv pip install .[docs]
    - .venv/bin/python -m sphinx -T -b html -d docs/_build/doctrees -D
      language=en docs $READTHEDOCS_OUTPUT/html
