"""
Implementation for the magnetic field of homogeneously
magnetized tetrahedra. Computation details in function docstrings.
"""
import numpy as np
from magpylib._src.fields.field_BH_facet import magnet_facet_field
from magpylib._src.input_checks import check_field_input


def check_chirality(points):
    """
    Checks if quartupel of points (p0,p1,p2,p3) that forms tetrahedron is arranged in a way
    that the vectors p0p1, p0p2, p0p3 forms a right-handed system

    Parameters
    -----------
    points: 3d-array of shape (m x 4 x 3)
            m...number of tetrahedrons

    Returns
    ----------
    new list of points, where p2 and p3 are possibly exchanged so that all
    tetrahedron is given in a right-handed system
    """

    vecs = np.zeros((len(points), 3, 3))
    vecs[:, :, 0] = points[:, 1, :] - points[:, 0, :]
    vecs[:, :, 1] = points[:, 2, :] - points[:, 0, :]
    vecs[:, :, 2] = points[:, 3, :] - points[:, 0, :]

    dets = np.linalg.det(vecs)
    dets_neg = dets < 0

    if np.any(dets_neg):
        points[dets_neg, 2:, :] = points[dets_neg, 3:1:-1, :]

    return points


def point_inside(points, vertices):
    """
    Takes points, as well as the vertices of a tetrahedra.
    Returns boolean array indicating whether the points are inside the tetrahedra.
    """
    mat = np.zeros((len(vertices), 3, 3))
    mat[:, 0, :] = vertices[:, 1, :] - vertices[:, 0, :]
    mat[:, 1, :] = vertices[:, 2, :] - vertices[:, 0, :]
    mat[:, 2, :] = vertices[:, 3, :] - vertices[:, 0, :]
    tetra = np.linalg.inv(np.transpose(mat, (0, 2, 1)))

    newp = np.matmul(tetra, np.reshape(points - vertices[:, 0, :], (*points.shape, 1)))
    return (
        np.all(newp >= 0, axis=1)
        & np.all(newp <= 1, axis=1)
        & (np.sum(newp, axis=1) <= 1)
    ).flatten()


# CORE
def magnet_tetrahedron_field(
    field: str,
    observers: np.ndarray,
    magnetization: np.ndarray,
    vertices: np.ndarray,
) -> np.ndarray:
    """Magnetic field generated by homogeneously magnetized tetrahedron.

    Parameters
    ----------
    field: str, default=`'B'`
        If `field='B'` return B-field in units of [mT], if `field='H'` return H-field
        in units of [kA/m].

    observers: ndarray, shape (n,3)
        Observer positions (x,y,z) in Cartesian coordinates in units of [mm].

    magnetization: ndarray, shape (n,3)
        Homogeneous magnetization vector in units of [mT].

    vertices: ndarray, shape (n,4,3)
        Vertices of the tetraeder [(pos1a, pos1b, pos1c, pos1d),
        (pos2a, pos2b, pos2c, pos2d), ...].

    Returns
    -------
    B-field or H-field: ndarray, shape (n,3)
        B/H-field of magnet in Cartesian coordinates (Bx, By, Bz) in units of [mT]/[kA/m].

    Notes
    -----
    The tetrahedron is built up via 4 faces applying the Facet class.
    """

    bh = check_field_input(field, "magnet_tetrahedron_field()")

    n = len(observers)

    vertices = check_chirality(vertices)
    facets_vertices = np.concatenate(
        (
            vertices[:, [0, 2, 1], :],
            vertices[:, [0, 1, 3], :],
            vertices[:, [1, 2, 3], :],
            vertices[:, [0, 3, 2], :],
        ),
        axis=0,
    )
    facets_fields = magnet_facet_field(
        field,
        np.tile(observers, (4, 1)),
        np.tile(magnetization, (4, 1)),
        facets_vertices,
    )
    field = (
        facets_fields[0:n, :]
        + facets_fields[n : 2 * n, :]
        + facets_fields[2 * n : 3 * n, :]
        + facets_fields[3 * n : 4 * n, :]
    )

    if bh:
        # if inside magnet add magnetization vector
        mask_inside = point_inside(observers, vertices)
        field[mask_inside] += magnetization[mask_inside]
        return field

    return field
