from itertools import compress

import numpy as np
import warnings
from magpylib._src.fields.field_wrap_BH import getB


def check_format_input_sources(sources):
    """
    Check and format sources input
    """
    if not isinstance(sources, list):
        sources = [sources]
    for s in sources:
        if not hasattr(s, '_field_func'):
            msg = (
                "getFT bad source input. Sources can only be Magpylib source objects."
                f" Instead received type {type(s)} source."
            )
            raise ValueError(msg)
    return sources


def check_format_input_targets(targets):
    """
    Check and format targets input
    - flatten Collections
    - check if allowed instance
    - check if meshing parameter is set
    
    Returns
    -------
    flat list of targets , list of collection indices for summation
    """
    if not isinstance(targets, list):
        targets = [targets]

    # flatten out collections, keep indices for later summation in getFT
    flat_targets = []
    coll_idx = []
    idx = 0
    for t in targets:
        from magpylib._src.obj_classes.class_Collection import Collection
        if isinstance(t, Collection):
            len_sources = len(t.sources_all)
            if len_sources == 0:
                msg = f"Given target Collection {t} has no target sources."
                raise ValueError(msg)
            flat_targets.extend(t.sources_all)
            coll_idx.append(idx)
            idx += len_sources
        else:
            flat_targets.append(t)
            coll_idx.append(idx)
            idx += 1

    # check if all flat_targets are valid
    for t in flat_targets:

        # exclude Dipole from check
        from magpylib._src.obj_classes.class_misc_Dipole import Dipole
        if not isinstance(t, (Dipole,)):

            if not hasattr(t, 'meshing'):
                msg = (
                    "getFT bad target input. Targets can only be Magpylib objects Cuboid,..."
                    f" Instead received type {type(t)} target."
                )
                raise ValueError(msg)

            # check if meshing parameter is explicitly set
            if t.meshing is None:
                msg = (
                    f"getFT missing meshing input for target {t}."
                    " All targets must have the meshing parameter explicitly set."
                )
                raise ValueError(msg)

    return flat_targets, coll_idx


def check_format_input_pivot(pivot, targets):
    """
    Check and format pivot input

    Returns
    -------
    np.array of pivots with shape (n_target, 3)
    """
    msg = (
        "Bad getFT pivot input. Input pivot must be str 'centroid', None or array_like of shape (3,)."
        " It can also be (n,3) when there are n targets providing a different pivot for every target."
    )

    if isinstance(pivot, str) and pivot == "centroid":
        return np.array([t.centroid for t in targets])

    if pivot is None:
        return None

    if isinstance(pivot, (list, tuple, np.ndarray)):
        try:
            pivot = np.array(pivot, dtype=float)
        except (ValueError, TypeError) as e:
            raise ValueError(msg) from e
        
        if pivot.shape == (3,):
            return np.tile(pivot, (len(targets), 1))
        if pivot.shape == (len(targets), 3):
            return pivot

    raise ValueError(msg)


def create_eps_vector(eps):
    """
    Create a vector of finite difference steps based on the input eps.
    
    Parameters
    ----------
    eps : float
        The finite difference step size.

    Returns
    -------
    np.ndarray
        A vector of shape (7, 3) for finite difference calculations.
    """
    return np.array(
        [
            (0, 0, 0),
            (eps, 0, 0),
            (-eps, 0, 0),
            (0, eps, 0),
            (0, -eps, 0),
            (0, 0, eps),
            (0, 0, -eps),
        ]
    )


def getFT(sources, targets, pivot="centroid", eps=1e-5, squeeze=True):
    """
    Compute magnetic force and torque acting on the targets that are exposed
    to the magnetic field of the sources.

    SI units are assumed for all inputs and outputs.

    Parameters
    ----------
    sources: source and collection objects or 1D list thereof
        Sources that generate the magnetic field. Can be a single source (or collection)
        or a 1D list of l sources and/or collection objects.

    targets: single object or 1D list of t objects that are Sphere, Cuboid, Polyline,
        Cylinder, CylinderSegment, or Dipole. Force and Torque acting on targets in the magnetic
        field generated by the sources will be computed. A target (except of Dipole) must have a valid
        `meshing` parameter.

    pivot: str, None, or array_like, default="centroid"
        The Force adds to the Torque via the pivot point. For a freely floating magnet
        this would be the barycenter (= centroid when the density is homogeneous).
        If pivot="centroid" the centroid is selected as the pivot point for all targets.
        If pivot=None no pivot is used. This will give unphysical results.
        If pivot=array_like of shape (3,) the same pivot is used for all targets.
        Alternatively one can provide an individual pivot point for each target.

    eps: float, default=1e-5
        This is only used for magnet targets for computing the magnetic field gradient
        using finite differences (FD). `eps` is the FD step size. A good value
        is 1e-5 * characteristic_system_size (magnet size, distance between sources
        and targets, ...).

    squeeze: bool, default=True
        The output of the computation has the shape (n,3) where n corresponds to the number
        of targets. By default this is reduced to (3,) when there is only one target.

    Returns
    -------
    Force-Torque as ndarray of shape (2,3), or (t,2,3) when t targets are given
    """
    # Input checks
    targets, coll_idx = check_format_input_targets(targets)
    pivot = check_format_input_pivot(pivot, targets)
    sources = check_format_input_sources(sources)

    # Get force types and create masks efficiently
    mask_magnet = np.array([tgt._force_type == "magnet" for tgt in targets])
    mask_current = np.array([tgt._force_type == "current" for tgt in targets])

    # Important numbers
    n_targets = len(targets)
    n_sources = len(sources)
    n_magnets = sum(mask_magnet)  # number of magnet targets
    n_currents = sum(mask_current)  # number of current targets

    # Allocate output arrays
    FTOUT = np.zeros((2, n_sources, n_targets, 3))

    # RUN MESHING FUNCTIONS ##############################################################
    # Collect meshing function results - cannot separate mesh generation from generation 
    #    of moments, lvecs, etc.
    # Meshing functions are run now to collect all observers because the B-field is
    #    computed for all targets at once, for efficiency reasons.
    observer = []
    mesh_sizes = []
    mag_moments = []
    cur_currents = []
    cur_tvecs = []
    eps_vec = create_eps_vector(eps)
    for tgt in targets:

        if tgt._force_type == "magnet":
            mesh, mom = tgt._generate_mesh()
            mag_moments.append(mom)
            # if target is a magnet add 6 finite difference steps for gradient computation
            mesh = (mesh[:, np.newaxis, :] + eps_vec[np.newaxis, :, :]).reshape(-1, 3)

        if tgt._force_type == "current":
            mesh, curr, tvec = tgt._generate_mesh()
            cur_currents.append(curr)
            cur_tvecs.append(tvec)

        observer.append(mesh)
        mesh_sizes.append(len(mesh))


    # COMPUTE B FIELD ###################################################################
    observer = np.concatenate(observer, axis=0)
    B_all = getB(sources, observer, squeeze=False)
    # shape (n_src, 1, 1, n_obs, 3)

    # Indexing of observer and B_all arrays
    mesh_sizes = np.array(mesh_sizes)
    obs_ends = np.cumsum(mesh_sizes)
    obs_starts = np.r_[0, obs_ends[:-1]]

    # COMPUTATION IDEA:
    #   The equations are very simple like F = DB.MOM, T = B x MOM.
    #   All we need to do is to broadcast into large computation arrays that
    #   contain DB, MOM, B, ... and apply the equations, sum over mesh cells,
    #   and reshape the output to the desired shape.

    # MAGNETS ########################################################################
    if n_magnets > 0:
        
        # Prepare index ranges for broadcasting
        mesh_sizes_mag = mesh_sizes[mask_magnet] // 7
        n_mesh_mag = sum(mesh_sizes_mag)
        idx_ends = np.cumsum(mesh_sizes_mag)
        idx_starts = np.r_[0, idx_ends[:-1]]

        # Computation array allocations
        POS = np.zeros((n_mesh_mag*n_sources, 3))   # central location of each cell
        B = np.zeros((n_mesh_mag*n_sources, 3))     # B-field at each cell
        DB = np.zeros((n_mesh_mag*n_sources, 3, 3)) # B-field gradient at each cell
        MOM = np.zeros((n_mesh_mag*n_sources, 3))   # magnetic moment of each cell

        # BROADCASTING into computation arrays:
        #   rule: (src1 mesh1, src1 mesh2, src1 mesh3, ... src2 mesh1, src2 mesh2, ... )
        for i, mom in enumerate(mag_moments):
            # range in observer and B arrays
            start = obs_starts[mask_magnet][i]
            end = obs_ends[mask_magnet][i]
            
            for j in range(n_sources):
                # range in computation arrays
                ids = idx_starts[i] + n_mesh_mag*j
                ide = idx_ends[i] + n_mesh_mag*j

                POS[ids : ide] = observer[start : end : 7]
                B[ids : ide] = B_all[j, 0, 0, start : end : 7]

                # ∂B/∂x
                DB[ids : ide, :, 0] = B_all[j, 0, 0, start+1 : end : 7]
                DB[ids : ide, :, 0] -= B_all[j, 0, 0, start+2 : end : 7]
                DB[ids : ide, :, 0] /= (2*eps)

                # ∂B/∂y
                DB[ids : ide, :, 1] = B_all[j, 0, 0, start+3 : end : 7]
                DB[ids : ide, :, 1] -= B_all[j, 0, 0, start+4 : end : 7]
                DB[ids : ide, :, 1] /= (2*eps)
                
                # ∂B/∂z
                DB[ids : ide, :, 2] = B_all[j, 0, 0, start+5 : end : 7]
                DB[ids : ide, :, 2] -= B_all[j, 0, 0, start+6 : end : 7]
                DB[ids : ide, :, 2] /= (2*eps)

                MOM[ids : ide] = mom

        # ACTUAL FORCE AND TORQUE COMPUTATION
        #   !!Performance!!: cross few time faster than einsum few times faster than array API.
        #   Torque computation relies on force computation.
        #   Therefore it makes no sense to separate the force and torque computation.

        force = np.einsum('ijk,ik->ij', DB, MOM) # numpy only
        #force = np.sum(DB * MOM[:, np.newaxis, :], axis=2) # array API
        torque = np.cross(MOM, B)

        # Add pivot point contribution to torque
        if pivot is not None:
            PIV = np.tile(np.repeat(pivot[mask_magnet], mesh_sizes_mag, axis=0), (n_sources, 1))
            torque += np.cross(POS - PIV, force)

        # Sum over mesh cells
        idx_starts_all = np.concatenate([idx_starts + n_mesh_mag*j for j in range(n_sources)])
        F = np.add.reduceat(force, idx_starts_all, axis=0)
        T = np.add.reduceat(torque, idx_starts_all, axis=0)

        # Broadcast into output arrays
        FTOUT[0, :, mask_magnet] = F.reshape(n_sources, n_magnets, 3).transpose(1, 0, 2)
        FTOUT[1, :, mask_magnet] = T.reshape(n_sources, n_magnets, 3).transpose(1, 0, 2)


    # CURRENTS ########################################################################
    if n_currents > 0:
        # Prepare index ranges for broadcasting
        mesh_sizes_cur = mesh_sizes[mask_current]
        n_mesh_cur = sum(mesh_sizes_cur)
        idx_ends = np.cumsum(mesh_sizes_cur)
        idx_starts = np.r_[0, idx_ends[:-1]]

        # Computation array allocations
        POS = np.zeros((n_mesh_cur*n_sources, 3))  # central location of each cell
        B = np.zeros((n_mesh_cur*n_sources, 3))    # B-field at POS
        TVEC = np.zeros((n_mesh_cur*n_sources, 3)) # current path tangential vectors
        CURR = np.zeros((n_mesh_cur*n_sources,))   # current

        # BROADCASTING into computation arrays:
        #   rule: (src1 mesh1, src1 mesh2, src1 mesh3, ... src2 mesh1, src2 mesh2, ... )
        for i, (curr, tvec) in enumerate(zip(cur_currents, cur_tvecs)):
            # range in observer and B arrays
            start = obs_starts[mask_current][i]
            end = obs_ends[mask_current][i]

            for j in range(n_sources):
                # range in computation arrays
                ids = idx_starts[i] + n_mesh_cur*j
                ide = idx_ends[i] + n_mesh_cur*j

                POS[ids : ide] = observer[start : end]
                B[ids : ide] = B_all[j, 0, 0, start : end]
                TVEC[ids : ide] = tvec
                CURR[ids : ide] = curr

        # ACTUAL FORCE AND TORQUE COMPUTATION
        force = (CURR * np.cross(TVEC, B).T).T
        torque = np.zeros_like(force)

        # Add pivot point contribution to torque
        if pivot is not None:
            PIV = np.tile(np.repeat(pivot[mask_current], mesh_sizes_cur, axis=0), (n_sources, 1))
            torque += np.cross(POS - PIV, force)

        # Sum over mesh cells
        idx_starts_all = np.concatenate([idx_starts + n_mesh_cur*j for j in range(n_sources)])
        F = np.add.reduceat(force, idx_starts_all, axis=0)
        T = np.add.reduceat(torque, idx_starts_all, axis=0)

        # Broadcast into output arrays
        FTOUT[0, :, mask_current] = F.reshape(n_sources, n_currents, 3).transpose(1, 0, 2)
        FTOUT[1, :, mask_current] = T.reshape(n_sources, n_currents, 3).transpose(1, 0, 2)

    # FINALIZE OUTPUT ##############################################################

    # Sum up Collections
    FTOUT = np.add.reduceat(FTOUT, coll_idx, axis=2)

    if squeeze:
        return np.squeeze(FTOUT)

    return FTOUT











#         # # force on every instance
#         # F = (CURR * np.cross(LVEC, B).T).T

#         # # torque on every instance + sumup for every target
#         # if anchor is not None:
#         #     T = np.cross(anchor - POSS, F)
#         #     T = np.array(
#         #         [np.sum(T[insti[i] : insti[i + 1]], axis=0) for i in range(tgt_number)]
#         #     )
#         # else:
#         #     T = np.zeros((tgt_number, 3))

#     return 0


#     # # split targets into lists of similar types
#     # TARGET_TYPES = [Cuboid, Polyline, Sphere, Cylinder, CylinderSegment, Circle, Dipole]
#     # getFT_FUNCS = [
#     #     getFTmagnet,
#     #     getFTcurrent,
#     #     getFTmagnet,
#     #     getFTmagnet,
#     #     getFTmagnet,
#     #     getFTcurrent_circ,
#     #     getFTdipole,
#     # ]
#     # objects = [[] for _ in TARGET_TYPES]
#     # orders = [[] for _ in TARGET_TYPES]

#     # for i, tgt in enumerate(targets):
#     #     for j, ttyp in enumerate(TARGET_TYPES):
#     #         if isinstance(tgt, ttyp):
#     #             objects[j].append(tgt)
#     #             orders[j].append(i)

#     # # allocate FT
#     # FT = np.zeros((n, 2, 3))

#     # # FT-computation and broadcasting
#     # for i in range(len(TARGET_TYPES)):
#     #     if objects[i]:
#     #         ft_part = getFT_FUNCS[i](sources, objects[i], eps=eps, anchor=anchor)
#     #         ft_part = np.swapaxes(ft_part, 0, 1)
#     #         for ft, j in zip(ft_part, orders[i], strict=False):
#     #             FT[j] = ft

#     # if squeeze:
#     #     return np.squeeze(FT)
#     # return FT


# def getFT_current():
#     """
#     Placeholder for force computation function.
#     This should be replaced with the actual implementation.
#     """
#     """
#     compute force acting on tgt Polyline
#     eps is a dummy variable that is not used

#     info:
#     targets = Polyline objects
#     segments = linear segments within Polyline objects
#     instances = computation instances, each segment is split into `meshing` points
#     """
#     # number of Polylines
#     tgt_number = len(targets)

#     # segments of each Polyline
#     seg_numbers = np.array([len(tgt.vertices) - 1 for tgt in targets])

#     # number of mesh-points of each Polyline
#     mesh_numbers = np.array([tgt.meshing for tgt in targets])

#     # number of instances of each Polyline
#     inst_numbers = seg_numbers * mesh_numbers

#     # total number of instances
#     no_inst = np.sum(inst_numbers)

#     # cumsum of number of instances (used for indexing)
#     insti = np.r_[0, np.cumsum(inst_numbers)]

#     # path vector of each instance
#     LVEC = np.zeros((no_inst, 3))
#     # central location of each instance
#     POSS = np.zeros((no_inst, 3))
#     # current of each instance
#     CURR = np.zeros((no_inst,))

#     for i, tgt in enumerate(targets):
#         verts = tgt.orientation.apply(tgt.vertices)
#         mesh = mesh_numbers[i]

#         lvec = np.repeat(verts[1:] - verts[:-1], mesh, axis=0) / mesh
#         LVEC[insti[i] : insti[i + 1]] = lvec

#         CURR[insti[i] : insti[i + 1]] = [tgt.current] * mesh * seg_numbers[i]

#         for j in range(seg_numbers[i]):
#             # pylint: disable=line-too-long
#             poss = (
#                 np.linspace(
#                     verts[j] + lvec[j * mesh] / 2,
#                     verts[j + 1] - lvec[j * mesh] / 2,
#                     mesh,
#                 )
#                 + tgt.position
#             )
#             POSS[insti[i] + mesh * j : insti[i] + mesh * (j + 1)] = poss

#     # field of every instance
#     B = magpy.getB(sources, POSS, sumup=True)

#     # force on every instance
#     F = (CURR * np.cross(LVEC, B).T).T

#     # torque on every instance + sumup for every target
#     if anchor is not None:
#         T = np.cross(anchor - POSS, F)
#         T = np.array(
#             [np.sum(T[insti[i] : insti[i + 1]], axis=0) for i in range(tgt_number)]
#         )
#     else:
#         T = np.zeros((tgt_number, 3))

#     # sumup force for every target
#     F = np.array(
#         [np.sum(F[insti[i] : insti[i + 1]], axis=0) for i in range(tgt_number)]
#     )

#     return np.array((F, -T))
    
    
    
    
    
#     warnings.warn("FT_current is a placeholder and should be replaced with an actual implementation.")
#     return np.zeros((1, 2, 3))  # Dummy return value


# def getFT_dipole():
#     """
#     Placeholder for force computation function.
#     This should be replaced with the actual implementation.
#     """
#     warnings.warn("FT_magnet is a placeholder and should be replaced with an actual implementation.")
#     return np.zeros((1, 2, 3))  # Dummy return value